apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: large-size
spec:
  annotationSelector: {}
  labelSelector:
    matchLabels:
      size: large
  templates:
    - excludedPaths:
        - .metadata
        - .status
        - .spec.replicas
      objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: large-size
          namespace: {{ .Name }}  
        spec:
          hard:
            requests.cpu: "16"
            requests.memory: "32Gi"
