apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 10
  name: dev-team-a
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev-team-a
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: spring-dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ocp-deployment.lastUpdated
          value: ""
        - name: ocp-deployment.image.tag
          value: 2022-12-14-445887
        - name: ocp-deployment.image.repository
          value: 'quay.io/mlacourse/spring-rest-demo'
    repoURL: 'https://malacourse.github.io/spring-rest'
    targetRevision: 2022-12-14-445887
  syncPolicy:
    automated:
      selfHeal: true

