apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '65536'
    machine.openshift.io/vCPU: '16'
  resourceVersion: '13834'
  name: cluster-k98gd-z9zvj-worker-us-east-2b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-k98gd-z9zvj
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-k98gd-z9zvj
      machine.openshift.io/cluster-api-machineset: cluster-k98gd-z9zvj-worker-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-k98gd-z9zvj
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-k98gd-z9zvj-worker-us-east-2b
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m5.4xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 100
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-k98gd-z9zvj-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/cluster-k98gd-z9zvj
              value: owned
            - name: Stack
              value: project ocp4-cluster-k98gd
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: k98gd
            - name: owner
              value: unknown
            - name: platform
              value: RHPDS
            - name: uuid
              value: 63606112-28bd-56fd-b339-c85d26998fa5
          deviceIndex: 0
          ami:
            id: ami-02c627a4f7f3cef78
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-k98gd-z9zvj-private-us-east-2b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-k98gd-z9zvj-worker-profile

