apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "worker-us-east-2a" 
  namespace: "openshift-machine-api"
spec:
  minReplicas: 2 
  maxReplicas: 12 
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet 
    name: cluster-k98gd-z9zvj-worker-us-east-2a
