apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "worker-us-east-1a" 
  namespace: "openshift-machine-api"
spec:
  minReplicas: 3 
  maxReplicas: 12 
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet 
    name: aro-cluster-8vjhx-tjqn2-worker-eastus1
