apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "65536"
    machine.openshift.io/vCPU: "16"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-w9cr9-zntb2
  name: cluster-w9cr9-zntb2-worker-us-east-2a
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-w9cr9-zntb2
      machine.openshift.io/cluster-api-machineset: cluster-w9cr9-zntb2-worker-us-east-2a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-w9cr9-zntb2
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-w9cr9-zntb2-worker-us-east-2a
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-0ff64f495c7e977cf
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-w9cr9-zntb2-worker-profile
          instanceType: m5a.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-w9cr9-zntb2-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-w9cr9-zntb2-private-us-east-2a
          tags:
          - name: kubernetes.io/cluster/cluster-w9cr9-zntb2
            value: owned
          - name: platform
            value: RHPDS
          - name: uuid
            value: b16d2796-343d-5367-9b9a-11cf8cb168ed
          - name: Stack
            value: project ocp4-cluster-w9cr9
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: w9cr9
          - name: owner
            value: unknown
          userDataSecret:
            name: worker-user-data
